name: Build ZMK Firmware

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    working-directory: togkey_zmk_source/zmk-config-pad-pocket
